#!/bin/bash
SUBCMD=$1
shift

## Prints out the paths for all libraries used
if [ $SUBCMD == "libpaths" ];
then
    Rscript -e 'cat(paste(.libPaths(), collapse=":"), "\\n")'
else
    echo "usage rutils .libPaths()"
fi


